[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "tcg mcube doc test"
authors = [{name = "Megabeth", email = "don.koch@tcgdigital.com"}]
dynamic = ["version", "description"]
